### ISSUE TITLE
Autogenerated Requests

### ISSUE THREAD

**Issue by stefnotch** [simonZweimueller/digital-signage-overlay#3]
This request right here has been autogenerated using Postman.
https://github.com/simonZweimueller/digital-signage-overlay/blob/c437cf4abf8655eecc694bdd378dfe97a5eb85eb/server.js#L17

However, just copying everything is a bad idea :tm: , because Postman generates requests that perfectly match the ones that it just fired off. So, it sets all sorts of useless headers (`"User-Agent": "PostmanRuntime/7.13.0"`), adds headers that you should leave out (`"content-length": "165"`), etc. 

If I didn't overlook anything, you should be able to trim down your request to
```javascript
var options = {
  method: 'PUT',
  url: 'http://localhost/api/playlist/widget/10', 
  headers:
  {
    Authorization: 'Bearer 70Do2KmWM3cynq51BHrf3lU6DLsZIKFuVWlkibkS',
    'Content-Type': 'application/x-www-form-urlencoded' 
  },
  form: { 
    duration: '100', 
    useDuration: '1' 
  }
  
  /*
  Some requests want a multipart/form-data, others want a application/x-www-form-urlencoded
  Xibo is weird.

  "Content-Type": "multipart/form-data"
  },
  formData : {
      "name" : "teat" 
  }
    */
};

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

By the way, the `PHPSESSID` cookie seems to be optional.

**Comment by tealeon** [comment]
The trimmed request works. It is as you said, the headers of Postman were the problem. Thank you for your help.

**Comment by stefnotch** [comment]
Glad to hear that. 😄
